// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/rooms": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/room/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/signup" | "/rooms" | "/profile" | "/room/:id";
  };
  "./layouts/BaseLayout.tsx": {
    id: "layouts/BaseLayout";
    page: "/" | "/login" | "/signup" | "/rooms" | "/profile" | "/room/:id";
  };
  "../pages/hero/ui/Page.tsx": {
    id: "../pages/hero/ui/Page";
    page: "/";
  };
  "../pages/login/ui/Page.tsx": {
    id: "../pages/login/ui/Page";
    page: "/login";
  };
  "../pages/signup/ui/Page.tsx": {
    id: "../pages/signup/ui/Page";
    page: "/signup";
  };
  "../pages/rooms/ui/Page.tsx": {
    id: "../pages/rooms/ui/Page";
    page: "/rooms";
  };
  "../pages/profile/ui/Page.tsx": {
    id: "../pages/profile/ui/Page";
    page: "/profile";
  };
  "../pages/room/ui/Page.tsx": {
    id: "../pages/room/ui/Page";
    page: "/room/:id";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "layouts/BaseLayout": typeof import("./src/app/./layouts/BaseLayout.tsx");
  "../pages/hero/ui/Page": unknown;
  "../pages/login/ui/Page": unknown;
  "../pages/signup/ui/Page": unknown;
  "../pages/rooms/ui/Page": unknown;
  "../pages/profile/ui/Page": unknown;
  "../pages/room/ui/Page": unknown;
};